### ISSUE TITLE
Error when i try to run npm serve

### ISSUE THREAD

**Issue by geekz** [creativetimofficial/ct-vue-now-ui-dashboard-pro#27]
murali@murali-U:/mnt/D0B8DC38B8DC1EB2/Users/murali kumar/jbd$ npm run serve

> vue-now-ui-dashboard-pro@1.1.0 serve /mnt/D0B8DC38B8DC1EB2/Users/murali kumar/jbd
> vue-cli-service serve --open

/mnt/D0B8DC38B8DC1EB2/Users/murali kumar/jbd/node_modules/@vue/cli-service/bin/vue-cli-service.js:4
const { error } = require('@vue/cli-shared-utils')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 4.4.0-143-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "serve"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! vue-now-ui-dashboard-pro@1.1.0 serve: `vue-cli-service serve --open`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-now-ui-dashboard-pro@1.1.0 serve script 'vue-cli-service serve --open'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-now-ui-dashboard-pro package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     vue-cli-service serve --open
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-now-ui-dashboard-pro
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-now-ui-dashboard-pro
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/D0B8DC38B8DC1EB2/Users/murali kumar/jbd/npm-debug.log
murali@murali-U:/mnt/D0B8DC38B8DC1EB2/Users/murali kumar/jbd$

**Comment by geekz** [comment]
I am not able to run it in my local development pc. with npm serve command. getting error "SyntaxError: Unexpected token {"
